const CUSTOM_ACTION_TYPE_SCHEDULE_EVENT = "schedule-action";
const BINDING_QUEUE_TYPE = "queue";
const BINDING_CUSTOM_KEY_EVENT = "event.custom";
const CUSTOM_ACTION_TYPE_BATCH_SCHEDULE_EVENTS = "schedule-events-action"

module.exports = {
  CUSTOM_ACTION_TYPE_SCHEDULE_EVENT,
  BINDING_QUEUE_TYPE,
  BINDING_CUSTOM_KEY_EVENT,
  CUSTOM_ACTION_TYPE_BATCH_SCHEDULE_EVENTS,
};
