// Homepage data contracts — Phase 1.
//
// SANITISED. The Magic Patterns generation returned invented reviews, invented
// star ratings and invented pool counts as placeholder content. Those are
// removed here rather than carried into the repo: house rule 1 is "never invent
// a person, testimonial, host quote, venue, or statistic", and a placeholder
// that looks real is exactly how the "Stephen, Founder" email shipped.
//
// Every array below is EMPTY on purpose. Each one is a slot to be filled from a
// real source at runtime — the sources are named per-type. If a source returns
// nothing, the section must render its empty state, never sample data.

export type Listing = {
  id: string;
  title: string;
  city: string;
  state: string;
  pricePerHour: number;
  image: string;
  amenities: string[];
  badges?: string[];
  /** Only ever set from a real review aggregate. Cards must look correct without one. */
  rating?: number;
  reviewCount?: number;
};

/** Source: searchSyncedListings() — the Supabase mirror, keyed by citySlug/stateCode. */
export const listings: Listing[] = [];

export type CitySuggestion = {
  city: string;
  state: string;
  /** Live count from the synced mirror. Omit the count rather than guess it. */
  poolCount?: number;
  /** Canonical destination, e.g. "/p/agoura-hills-ca". Never constructed by regex. */
  href: string;
};

/** Source: curated city table joined to live inventory. See RESOLVER notes in README. */
export const citySuggestions: CitySuggestion[] = [];

export type Occasion = { label: string; image: string; href: string | null };

/** href null = no destination page exists yet; render the tile unlinked or omit it. */
export const occasions: Occasion[] = [];

export type SeasonalCard = {
  title: string;
  description: string;
  image: string;
  /** null when the destination 404s. Verified 2026-09-04: only heated resolves. */
  href: string | null;
};

export const seasonalCards: SeasonalCard[] = [];

export type Market = { city: string; state: string; poolCount?: number; href: string };

/** Source: market score (GSC clicks, live inventory, bookings, impressions, season). */
export const markets: Market[] = [];

export type Review = { quote: string; name: string; city: string };

/** Source: real guest reviews only. No placeholder quotes, ever. */
export const reviews: Review[] = [];

export type Course = { title: string; meta: string; image: string; href: string };

export const courses: Course[] = [];

export type Faq = { question: string; answer: string };

/**
 * Renter-facing FAQ. The eight entries generated by the design are safe and
 * carry no fee or insurance claims, so they live in the README for review.
 *
 * The live homepage today also carries an insurance Q/A whose wording is
 * founder-owned. It is deliberately NOT reproduced here. It must be carried
 * across verbatim from production, not re-derived — and dropping it is a schema
 * change to an indexed FAQPage, so it is a decision, not a side effect.
 */
export const faqs: Faq[] = [];

/** Hero art: replace with a real PRNM listing photograph, responsive srcset, explicit dimensions. */
export const heroImage = '';
export const hostImage = '';
