/**
 * Host Academy — Course Catalog
 * ──────────────────────────────
 * The complete PoolRentalNearMe host curriculum. ~120 courses bucketed into
 * 8 tracks, organized into 3 certification tiers.
 *
 * Courses are delivered via OpenELMS iframes:
 *   https://openelms.ai/embed/{openElmsId}/
 *
 * This file is the single source of truth for:
 *  1. Certification ladder (Certified → Professional → Master)
 *  2. Track browsing on /host-academy
 *  3. Reactive coaching engine (problem event → trigger match → course)
 *  4. Listing page certification badges
 *
 * Content updates happen in THIS file — no code changes needed to add,
 * reorder, or re-tag courses.
 */

// ─── Feature flags ──────────────────────────────────────
// Certification badge is INTERNAL-ONLY until we have a critical mass of
// certified hosts. When this is false, badges render only on internal host
// surfaces (dashboard, academy page). They do NOT appear on listing pages,
// search results, or public profiles — guests shouldn't see the badge until
// a meaningful portion of hosts carry it, otherwise it becomes a negative
// signal for uncertified hosts rather than a positive one for certified ones.
export const HOST_ACADEMY_PUBLIC_BADGE_ENABLED = false;

// ─── Tracks ─────────────────────────────────────────────
export const TRACKS = {
  safety: {
    id: 'safety',
    name: 'Safety Essentials',
    short: 'Safety',
    tagline: 'The non-negotiable foundation',
    description:
      'Every certified PRNM host completes this track. It covers water rescue, supervision, drowning response, CPR, slip & fall prevention, and incident response — the standards that let us promise guests a safe experience at any PRNM listing.',
    icon: '⛑',
    accent: '#c94a5a',
    required: true,
  },
  operations: {
    id: 'operations',
    name: 'Pool Operations',
    short: 'Ops',
    tagline: 'Keep the pool guest-ready, always',
    description:
      'Water chemistry, equipment care, maintenance cadence, and smart-tech automation. This track teaches the SOPs that keep water crystal clear and equipment running — the mechanical half of a five-star experience.',
    icon: '⚙',
    accent: '#5b9dd9',
    required: true,
  },
  hospitality: {
    id: 'hospitality',
    name: 'Guest Hospitality',
    short: 'Hospitality',
    tagline: 'Five-star service, every booking',
    description:
      'Check-in protocols, guest communication, conflict resolution, and VIP repeat-guest playbooks. This is where Starter hosts become hosts that guests rebook.',
    icon: '☆',
    accent: '#d4af37',
    required: true,
  },
  legal: {
    id: 'legal',
    name: 'Legal & Compliance',
    short: 'Legal',
    tagline: 'Protect your home, your income, and your guests',
    description:
      'Insurance, waivers, LLC formation, tax strategy, HOA defense, surveillance law, and alcohol/cannabis liability. The safety net that keeps a host in business.',
    icon: '§',
    accent: '#9b7bbf',
    required: true,
  },
  marketing: {
    id: 'marketing',
    name: 'Marketing & Listings',
    short: 'Marketing',
    tagline: 'Get found, get booked',
    description:
      'Listing optimization, Google My Business, social ads, Nextdoor, TikTok, E-E-A-T copywriting, and the booking funnel. Turn a good pool into a booked-solid calendar.',
    icon: '↗',
    accent: '#3ba776',
    required: false,
  },
  revenue: {
    id: 'revenue',
    name: 'Revenue & Pricing',
    short: 'Revenue',
    tagline: 'Charge what you\u2019re worth',
    description:
      'Dynamic pricing, price variations, package design, upselling, cost-per-swim modeling, and turnover optimization. The math that separates $500/mo hosts from $10K/mo hosts.',
    icon: '$',
    accent: '#e6c55a',
    required: false,
  },
  events: {
    id: 'events',
    name: 'Events & Niche Hosting',
    short: 'Events',
    tagline: 'Unlock high-revenue occasions',
    description:
      'Weddings, birthdays, baptisms, corporate retreats, scuba certifications, fitness bootcamps, therapeutic programs. Specialized tracks that open new revenue streams.',
    icon: '✦',
    accent: '#c98a3c',
    required: false,
  },
  growth: {
    id: 'growth',
    name: 'Brand & Growth',
    short: 'Growth',
    tagline: 'From side hustle to empire',
    description:
      'Branding, automation, multi-property management, scaling, and the $10K-month blueprint. For hosts who want to go pro.',
    icon: '◆',
    accent: '#8ddcb5',
    required: false,
  },
};

// ─── Certification tiers ────────────────────────────────
export const CERTIFICATION_TIERS = {
  'certified': {
    id: 'certified',
    label: 'PRNM Certified Host',
    short: 'Certified',
    tagline: 'Safety + Operations + Hospitality basics',
    description:
      'This host has completed the PoolRentalNearMe Certified Host curriculum — the same training every host on our platform completes. Core safety protocols, pool operations, guest check-in, and legal compliance.',
    accent: '#3ba776',
    badgeEmoji: '✓',
    priceMultiplier: 1.05,
    requiredCourseCount: 30,
  },
  'professional': {
    id: 'professional',
    label: 'PRNM Professional Host',
    short: 'Professional',
    tagline: 'Everything Certified, plus marketing and advanced hospitality',
    description:
      'Professional Hosts have completed the full Certified curriculum plus advanced hospitality, marketing, and revenue tracks — the hosts who run pool rentals like a real business.',
    accent: '#d4af37',
    badgeEmoji: '★',
    priceMultiplier: 1.10,
    requiredCourseCount: 70,
  },
  'master': {
    id: 'master',
    label: 'PRNM Master Host',
    short: 'Master',
    tagline: 'Completed the full 120+ course curriculum',
    description:
      'Master Hosts have completed every track in the PRNM Academy. Hand-picked for featured placement, premium price recommendations, and first access to new platform features.',
    accent: '#e6c55a',
    badgeEmoji: '♔',
    priceMultiplier: 1.15,
    requiredCourseCount: 120,
  },
};

// ─── Course catalog ─────────────────────────────────────
// Each course:
//   id — internal stable id
//   openElmsId — embed id after /embed/ in the OpenELMS URL (null if unknown)
//   title, description, track
//   tier — minimum tier this course contributes to ('certified' | 'professional' | 'master')
//   language — 'en' | 'es'
//   triggers — array of problem event tags the reactive engine matches against
//   sopTags — array of SOP concepts this course teaches (used for search + tagging)
export const COURSES = [
  // ─── Safety Essentials ───
  {
    id: 'cpr-certified',
    openElmsId: 'e68493965098e06.68340618', title: 'How to Get CPR Certified',
    description: 'Comprehensive guide to obtaining CPR certification, covering major organizations, certification types, and class formats.',
    track: 'safety',
    tier: 'certified',
    language: 'en',
    triggers: ['incident-reported', 'host-onboarding'],
    sopTags: ['cpr', 'rescue', 'emergency'],
  },
  {
    id: 'pool-safety-hosts',
    openElmsId: 'e67f04efc6e5b68.07865843', title: 'Swimming Pool Safety for Hosts',
    description: 'Essential safety guidelines for pool hosts renting out their pools — safety measures, emergency protocols, liability reduction.',
    track: 'safety',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding', 'guest-complained-safety'],
    sopTags: ['safety-protocols', 'emergency'],
  },
  {
    id: 'clean-water-management',
    openElmsId: 'e681da3cd18d7d3.29901591', title: 'Clean Water Management for Pool Rentals',
    description: 'Essential guidelines for maintaining clean and safe pool water — testing, chemical balance, visibility standards.',
    track: 'safety',
    tier: 'certified',
    language: 'en',
    triggers: ['guest-complained-water', 'review-below-4-cleanliness'],
    sopTags: ['water-chemistry', 'cleanliness'],
  },
  {
    id: 'water-watcher-supervision',
    openElmsId: 'e68492fcaebae15.02971244', title: 'Water Safety: Designated Supervision',
    description: 'Importance of designated supervision and Water Watcher systems for drowning prevention.',
    track: 'safety',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding', 'incident-near-drowning'],
    sopTags: ['supervision', 'drowning-prevention'],
  },
  {
    id: 'drowning-response',
    openElmsId: 'e6842a0d6847656.18012009', title: 'Drowning Response in Pools',
    description: 'Essential guidance on how to respond effectively if someone is drowning.',
    track: 'safety',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding', 'incident-near-drowning'],
    sopTags: ['emergency', 'rescue'],
  },
  {
    id: 'slip-fall-prevention',
    openElmsId: 'e6842a2858578d4.23249509', title: 'Preventing Slip and Falls in Your Pool Area',
    description: 'Practical tips and strategies to prevent slip and fall accidents around your pool.',
    track: 'safety',
    tier: 'certified',
    language: 'en',
    triggers: ['incident-slip-fall', 'host-onboarding'],
    sopTags: ['safety-protocols', 'deck-safety'],
  },
  {
    id: 'water-rescue-equipment',
    openElmsId: 'e6849329e37d9e1.49487759', title: 'Water Rescue Equipment: Life Ring vs. Shepherd\u2019s Hook',
    description: 'Comprehensive guide on the correct use of life rings and shepherd\u2019s hooks.',
    track: 'safety',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding'],
    sopTags: ['rescue-equipment', 'emergency'],
  },
  {
    id: 'advanced-water-chemistry',
    openElmsId: 'e6870e5872f0623.08161517', title: 'Advanced Water Chemistry for Pool Hosts',
    description: 'Moving beyond basic maintenance to a scientific understanding of pool water chemistry.',
    track: 'safety',
    tier: 'professional',
    language: 'en',
    triggers: ['guest-complained-water', 'review-below-4-cleanliness'],
    sopTags: ['water-chemistry', 'maintenance'],
  },
  {
    id: 'waterborne-illness-prevention',
    openElmsId: 'e6896b2e2e6b227.81008453', title: 'Waterborne Illness Prevention Guide',
    description: 'Minimize recreational water illness risks with multi-barrier sanitation strategies.',
    track: 'safety',
    tier: 'professional',
    language: 'en',
    triggers: ['guest-complained-sickness', 'host-onboarding'],
    sopTags: ['sanitation', 'health-safety'],
  },
  {
    id: 'eap-incident-response',
    openElmsId: 'e6896aefee48497.63644663', title: 'Emergency Action Planning (EAP) & Incident Response Guide',
    description: 'Foundational understanding of emergency action planning and incident response.',
    track: 'safety',
    tier: 'certified',
    language: 'en',
    triggers: ['incident-reported', 'host-onboarding'],
    sopTags: ['emergency', 'incident-response'],
  },

  // ─── Pool Operations ───
  {
    id: 'pool-host-prep',
    openElmsId: 'e681da6e9c3e445.12908744', title: 'Pool Host Prep Guide',
    description: 'Ensures pool rental hosts prepare their pools to be spotless, safe, and guest-ready for every booking.',
    track: 'operations',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding', 'review-below-4-cleanliness'],
    sopTags: ['turnover', 'prep', 'cleanliness'],
  },
  {
    id: 'equipment-troubleshooting',
    openElmsId: 'e68bf754bc612b2.16029052', title: 'Pool Equipment Troubleshooting & Repair Guide',
    description: 'Troubleshoot and perform basic repairs on common pool equipment.',
    track: 'operations',
    tier: 'professional',
    language: 'en',
    triggers: ['equipment-failure-reported'],
    sopTags: ['equipment', 'maintenance'],
  },
  {
    id: 'smart-pool-tech',
    openElmsId: 'e693fbb99099ec8.04901762', title: 'Smart Pool Technology Stack for Hosts',
    description: 'The essential smart pool technology stack — automation, control, and security.',
    track: 'operations',
    tier: 'professional',
    language: 'en',
    triggers: ['efficiency-coaching'],
    sopTags: ['automation', 'smart-tech'],
  },
  {
    id: 'eco-sanitization',
    openElmsId: 'e69aff0780c2656.24619138', title: 'Eco-Friendly & Alternative Sanitization Pools',
    description: 'For hosts running saltwater, UV, or ozone pool systems — sanitation protocols and guest messaging.',
    track: 'operations',
    tier: 'professional',
    language: 'en',
    triggers: ['guest-asked-saltwater', 'water-quality-issue'],
    sopTags: ['sanitation', 'saltwater', 'ozone'],
  },
  {
    id: 'pool-heating-economics',
    openElmsId: 'e691ef9d6ef82e6.81502457', title: 'Pool Heating Economics: Pricing & Management',
    description: 'Financial aspects of pool heating and pricing strategies around heated rentals.',
    track: 'operations',
    tier: 'professional',
    language: 'en',
    triggers: ['pricing-coaching'],
    sopTags: ['heating', 'pricing'],
  },
  {
    id: 'broken-glass-nightmare',
    openElmsId: 'e696636091bca29.94325584', title: 'The Broken Glass Nightmare: Remediation & Liability',
    description: 'Critical protocols for broken glass incidents in pool environments where water contamination is a concern.',
    track: 'operations',
    tier: 'certified',
    language: 'en',
    triggers: ['incident-broken-glass', 'incident-reported'],
    sopTags: ['incident-response', 'liability'],
  },
  {
    id: 'signage-essentials',
    openElmsId: 'e681be8115af028.35900237', title: 'Essential Pool Rental Signage',
    description: 'Guidelines for placement and wording of essential pool rental signs.',
    track: 'operations',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding'],
    sopTags: ['signage', 'safety-protocols'],
  },
  {
    id: 'outdoor-lighting',
    openElmsId: 'e68ef4ebace4837.01560639', title: 'Outdoor Lighting for Safety & Ambiance',
    description: 'Enhance safety, security, and aesthetic appeal with the right outdoor lighting.',
    track: 'operations',
    tier: 'professional',
    language: 'en',
    triggers: ['ambiance-coaching'],
    sopTags: ['lighting', 'ambiance', 'safety'],
  },
  {
    id: 'furniture-decor',
    openElmsId: 'e691efabf3726b0.79085131', title: 'Durable Design: Selecting Pool Furniture & Decor',
    description: 'Selecting robust pool furniture and decor designed for high-traffic use.',
    track: 'operations',
    tier: 'professional',
    language: 'en',
    triggers: ['furniture-damaged', 'listing-quality-coaching'],
    sopTags: ['furniture', 'durability'],
  },
  {
    id: 'landscaping-privacy',
    openElmsId: 'e691efa4fd62193.42477284', title: 'Landscaping for Privacy & Noise Reduction',
    description: 'Use landscaping to create a secluded oasis and buffer sound from neighbors.',
    track: 'operations',
    tier: 'professional',
    language: 'en',
    triggers: ['neighbor-complaint-noise'],
    sopTags: ['landscaping', 'noise', 'privacy'],
  },
  {
    id: 'inventory-management',
    openElmsId: 'e691ef992e33195.03142308', title: 'Inventory Management: Towels, Toys & Loss Prevention',
    description: 'Strategies for tracking inventory with minimal guest intrusion.',
    track: 'operations',
    tier: 'professional',
    language: 'en',
    triggers: ['inventory-loss'],
    sopTags: ['inventory', 'loss-prevention'],
  },
  {
    id: '15-min-turnover',
    openElmsId: 'e693fba62ab86b8.27369083', title: 'The 15-Minute Turnover System: Maximizing Daily Bookings',
    description: 'Strategic cleaning-and-prep system that lets hosts book back-to-back sessions in the same day.',
    track: 'operations',
    tier: 'certified',
    language: 'en',
    triggers: ['efficiency-coaching', 'low-utilization'],
    sopTags: ['turnover', 'efficiency', 'sop'],
  },
  {
    id: 'automation-guide',
    openElmsId: 'e68bf7574d3e929.83060380', title: 'Complete Pool Rental Automation Guide',
    description: 'Establishing a fully automated pool rental business for passive income.',
    track: 'operations',
    tier: 'master',
    language: 'en',
    triggers: ['scale-coaching'],
    sopTags: ['automation', 'passive-income'],
  },

  // ─── Guest Hospitality ───
  {
    id: 'guest-communication-conflict',
    openElmsId: 'e6870cce398ce86.30330276', title: 'Guest Communication & Conflict Resolution Masterclass',
    description: 'Elevate guest interactions and adeptly manage conflicts.',
    track: 'hospitality',
    tier: 'certified',
    language: 'en',
    triggers: ['guest-complained', 'dispute-opened', 'review-below-4-communication'],
    sopTags: ['communication', 'conflict'],
  },
  {
    id: 'five-star-checkin',
    openElmsId: 'e681be9a80d0396.77972891', title: 'Five-Star Guest Check-In: Self and In-Person',
    description: 'Comprehensive guide to checking in guests — privacy, feedback, and first-impression strategies.',
    track: 'hospitality',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding', 'review-below-4-checkin'],
    sopTags: ['check-in', 'first-impression', 'sop'],
  },
  {
    id: 'guest-etiquette',
    openElmsId: 'e681da3b34b5774.97345774', title: 'Guest Pool Etiquette Guide',
    description: 'Essential guidelines for ensuring a safe and enjoyable pool experience.',
    track: 'hospitality',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding'],
    sopTags: ['etiquette', 'house-rules'],
  },
  {
    id: 'customer-safety',
    openElmsId: 'e67f095ffbc47f6.46757937', title: 'Customer Safety Guide',
    description: 'Essential guidelines for ensuring guest safety and proper conduct during a rental.',
    track: 'hospitality',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding'],
    sopTags: ['safety', 'house-rules'],
  },
  {
    id: 'guest-psychology',
    openElmsId: 'e6870e6e2c282c6.73471348', title: 'Guest Psychology & Experience Design Masterclass',
    description: 'Transforms pool rental hosts from basic service providers into experience designers.',
    track: 'hospitality',
    tier: 'professional',
    language: 'en',
    triggers: ['review-below-4', 'booking-rate-low'],
    sopTags: ['experience-design', 'psychology'],
  },
  {
    id: 'repeat-guest-mastery',
    openElmsId: 'e6870ec6d3833d1.48666345', title: 'Repeat Guest Mastery: Building Your VIP Client Base',
    description: 'Cultivate a loyal base of repeat guests — transforming one-time visitors into VIP clients.',
    track: 'hospitality',
    tier: 'professional',
    language: 'en',
    triggers: ['repeat-rate-low'],
    sopTags: ['retention', 'vip', 'loyalty'],
  },
  {
    id: 'difficult-guest-scenarios',
    openElmsId: 'e68ef4ddad08d91.24897625', title: 'Dealing with Difficult Guest Scenarios',
    description: 'Navigate the most challenging guest situations that can impact revenue and reputation.',
    track: 'hospitality',
    tier: 'certified',
    language: 'en',
    triggers: ['dispute-opened', 'guest-complained'],
    sopTags: ['conflict', 'de-escalation'],
  },
  {
    id: 'psychology-of-5-star-reviews',
    openElmsId: 'e693fbab6219e44.71216679', title: 'The Psychology of 5-Star Reviews: Engineered Delight',
    description: 'Psychological principles behind generating positive customer reviews.',
    track: 'hospitality',
    tier: 'professional',
    language: 'en',
    triggers: ['review-below-5', 'coaching'],
    sopTags: ['reviews', 'delight'],
  },
  {
    id: 'boundary-setting',
    openElmsId: 'e693fb9607df9d6.30909576', title: 'Boundary Setting Without Losing Bookings',
    description: 'Establish clear boundaries with guests while protecting property and staying bookable.',
    track: 'hospitality',
    tier: 'professional',
    language: 'en',
    triggers: ['property-damaged', 'house-rules-violated'],
    sopTags: ['boundaries', 'house-rules'],
  },
  {
    id: 'preventing-issues',
    openElmsId: 'e681beb455a0d55.57379118', title: 'Preventing Issues Before They Start',
    description: 'Strategies to prevent and manage issues with guests proactively.',
    track: 'hospitality',
    tier: 'professional',
    language: 'en',
    triggers: ['coaching'],
    sopTags: ['prevention', 'proactive-communication'],
  },
  {
    id: 'problem-renters',
    openElmsId: 'e6896bc1c61e702.86808637', title: 'Managing Problem (High-Risk or Non-Compliant) Renters',
    description: 'Effectively manage challenging guest behaviors and high-risk bookings.',
    track: 'hospitality',
    tier: 'professional',
    language: 'en',
    triggers: ['high-risk-booking', 'dispute-opened'],
    sopTags: ['risk-management', 'screening'],
  },

  // ─── Legal & Compliance ───
  {
    id: 'insurance-legal-essentials',
    openElmsId: 'e681bed0d0900a6.86172834', title: 'Insurance & Legal Essentials for Pool Hosts',
    description: 'Essential information on legal and insurance responsibilities for pool hosts.',
    track: 'legal',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding'],
    sopTags: ['insurance', 'legal', 'liability'],
  },
  {
    id: 'regulatory-compliance',
    openElmsId: 'e6896b97ceeea47.99552327', title: 'Regulatory & Compliance Essentials Guide',
    description: 'Foundational understanding of regulatory and compliance requirements.',
    track: 'legal',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding'],
    sopTags: ['compliance', 'regulation'],
  },
  {
    id: 'liability-waivers',
    openElmsId: 'e68ef50092bf989.26641705', title: 'Liability Waivers That Actually Protect You',
    description: 'Comprehensive guide to understanding and creating effective liability waivers.',
    track: 'legal',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding', 'dispute-opened'],
    sopTags: ['waivers', 'liability', 'legal'],
  },
  {
    id: 'forming-llc',
    openElmsId: 'e68ef4ff5bd6325.22772796', title: 'Forming an LLC for Your Pool Business',
    description: 'Process of forming an LLC — tax benefits and liability protection.',
    track: 'legal',
    tier: 'professional',
    language: 'en',
    triggers: ['growth-coaching'],
    sopTags: ['llc', 'business-formation'],
  },
  {
    id: 'tax-implications',
    openElmsId: 'e6870cbd44263d3.03499692', title: 'Tax Implications for Pool Rental Income',
    description: 'Essential tax obligations for pool rental hosts.',
    track: 'legal',
    tier: 'professional',
    language: 'en',
    triggers: ['tax-season', 'growth-coaching'],
    sopTags: ['taxes', 'accounting'],
  },
  {
    id: 'community-guidelines',
    openElmsId: 'e687f4ce8aec444.63670724', title: 'Community Guidelines: Conduct, Violence, Harassment, Sexual Misconduct',
    description: 'Overview of essential community guidelines and zero-tolerance policies.',
    track: 'legal',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding', 'incident-misconduct'],
    sopTags: ['community-standards', 'conduct'],
  },
  {
    id: 'cease-desist-response',
    openElmsId: 'e69663dc5578672.06959967',
    title: 'Student Swipe File: Response to a "Cease & Desist" Letter',
    description: 'How homeowners should effectively respond to an HOA "Cease & Desist" letter.',
    track: 'legal',
    tier: 'professional',
    language: 'en',
    triggers: ['hoa-threat', 'cease-desist-received'],
    sopTags: ['hoa', 'legal-response'],
  },
  {
    id: 'hoa-warfare',
    openElmsId: 'e69663d62351a13.12079690', title: 'HOA Warfare: Bypass Restrictions & Rent Your Pool',
    description: 'Strategies to navigate and potentially bypass HOA restrictions when renting out a private pool.',
    track: 'legal',
    tier: 'professional',
    language: 'en',
    triggers: ['hoa-threat', 'host-onboarding-hoa'],
    sopTags: ['hoa', 'legal-strategy'],
  },
  {
    id: 'hostile-neighbor-cease-desist',
    openElmsId: 'e69663d36b15b47.80866503', title: '(Hostile Neighbor): The "Cease & Desist" / Anti-Harassment Notice',
    description: 'Comprehensive guide to issuing a cease & desist or anti-harassment notice to a hostile neighbor.',
    track: 'legal',
    tier: 'professional',
    language: 'en',
    triggers: ['neighbor-harassment'],
    sopTags: ['neighbor-dispute', 'legal-response'],
  },
  {
    id: 'blue-lights-police',
    openElmsId: 'e69663d15f21687.75687776', title: 'Blue Lights in the Driveway — Managing Police Intervention',
    description: 'Essential strategies for property owners managing police intervention at rental properties.',
    track: 'legal',
    tier: 'professional',
    language: 'en',
    triggers: ['police-called', 'incident-reported'],
    sopTags: ['police', 'de-escalation', 'legal'],
  },
  {
    id: 'fence-war-neighbor',
    openElmsId: 'e69663bc323d693.83683565', title: 'The Fence War — De-escalating Neighbor Harassment',
    description: 'Essential strategies for managing and de-escalating neighbor harassment.',
    track: 'legal',
    tier: 'professional',
    language: 'en',
    triggers: ['neighbor-harassment', 'neighbor-complaint'],
    sopTags: ['neighbor-dispute', 'de-escalation'],
  },
  {
    id: 'surveillance-laws',
    openElmsId: 'e696636e91ee811.25598494', title: 'Surveillance Laws: Cameras vs. Privacy',
    description: 'Complex legal landscape surrounding surveillance cameras and individual privacy rights.',
    track: 'legal',
    tier: 'professional',
    language: 'en',
    triggers: ['camera-compliance', 'guest-privacy-concern'],
    sopTags: ['cameras', 'privacy', 'legal'],
  },
  {
    id: 'augusta-rule',
    openElmsId: 'e696636091a13b9.83575802', title: 'The "Augusta Rule" Masterclass: Tax-Free Income',
    description: 'IRS Section 280A strategy — rent your primary residence up to 14 days tax-free.',
    track: 'legal',
    tier: 'master',
    language: 'en',
    triggers: ['tax-coaching'],
    sopTags: ['taxes', 'tax-strategy', 'augusta-rule'],
  },
  {
    id: 'fighting-city-hall',
    openElmsId: 'e696638a45729c0.59525000', title: 'Fighting City Hall: Advocacy Against Rental Bans',
    description: 'Empower short-term rental hosts to advocate against restrictive rental bans.',
    track: 'legal',
    tier: 'master',
    language: 'en',
    triggers: ['rental-ban-threat'],
    sopTags: ['advocacy', 'zoning', 'legal'],
  },
  {
    id: 'bulletproof-rental-agreement',
    openElmsId: 'e693fbdfe277aa7.39691265', title: 'The Bulletproof Rental Agreement: Legal Protection That Actually Works',
    description: 'Landlord and property-manager knowledge for drafting legally sound rental agreements.',
    track: 'legal',
    tier: 'professional',
    language: 'en',
    triggers: ['host-onboarding', 'dispute-opened'],
    sopTags: ['rental-agreement', 'legal', 'waivers'],
  },
  {
    id: 'alcohol-cannabis-liability',
    openElmsId: 'e693fba087d3f02.33316321', title: 'Alcohol, Cannabis & Liability: What Hosts Must Know',
    description: 'Critical legal and practical aspects of managing alcohol and cannabis at pool rentals.',
    track: 'legal',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding', 'alcohol-incident'],
    sopTags: ['alcohol', 'cannabis', 'liability'],
  },
  {
    id: 'privacy-security-cameras',
    openElmsId: 'e69aff110dd6509.60340149', title: 'Privacy vs. Security: Camera & Noise Monitor Compliance',
    description: 'Balance guest privacy and property security across cameras and noise monitors.',
    track: 'legal',
    tier: 'professional',
    language: 'en',
    triggers: ['camera-compliance', 'guest-privacy-concern'],
    sopTags: ['cameras', 'noise-monitoring', 'privacy'],
  },
  {
    id: 'alcohol-policy-management',
    openElmsId: 'e68ef4e9f6a7477.46181039', title: 'Alcohol Policy & Liability Management',
    description: 'Managing alcohol-related risks and handling guest intoxication.',
    track: 'legal',
    tier: 'certified',
    language: 'en',
    triggers: ['alcohol-incident', 'house-rules-violated'],
    sopTags: ['alcohol', 'liability'],
  },

  // ─── Marketing & Listings ───
  {
    id: 'google-ads-social',
    openElmsId: 'e6870cd591b7504.09570377', title: 'Google Ads, Facebook, Instagram & Nextdoor Marketing',
    description: 'Leverage digital advertising platforms to increase bookings.',
    track: 'marketing',
    tier: 'professional',
    language: 'en',
    triggers: ['booking-rate-low', 'marketing-coaching'],
    sopTags: ['paid-ads', 'social-media'],
  },
  {
    id: 'market-rent-pool',
    openElmsId: 'e67f51524905ca8.63326826', title: 'Market & Rent Your Pool: A Hands-On Guide',
    description: 'Establish a strong online presence with website and directory strategies.',
    track: 'marketing',
    tier: 'professional',
    language: 'en',
    triggers: ['booking-rate-low'],
    sopTags: ['listing', 'directories'],
  },
  {
    id: 'listing-optimization',
    openElmsId: 'e6896b11c4650d3.42521089', title: 'Listing Optimization Guide: Photography, Copy & Conversion Science',
    description: 'Essential strategies for optimizing your listing for conversions.',
    track: 'marketing',
    tier: 'professional',
    language: 'en',
    triggers: ['listing-quality-coaching', 'booking-rate-low'],
    sopTags: ['listing', 'photography', 'copy'],
  },
  {
    id: 'google-business-profile',
    openElmsId: 'e6905429a321268.37031238', title: 'Google Business Profile Mastery',
    description: 'Master your Google Business Profile — driving local discovery and bookings.',
    track: 'marketing',
    tier: 'professional',
    language: 'en',
    triggers: ['booking-rate-low'],
    sopTags: ['gbp', 'local-seo'],
  },
  {
    id: 'google-my-business-domination',
    openElmsId: 'e693fb8b9be79c0.51054229', title: 'Google My Business Domination for Pool Hosts',
    description: 'Leverage Google My Business for maximum visibility and bookings.',
    track: 'marketing',
    tier: 'professional',
    language: 'en',
    triggers: ['booking-rate-low'],
    sopTags: ['gbp', 'local-seo'],
  },
  {
    id: 'short-form-video-ads',
    openElmsId: 'e69054134d02546.41118007', title: 'Short-Form Video Ads That Book',
    description: 'Practical strategies for creating high-converting short-form video ads.',
    track: 'marketing',
    tier: 'master',
    language: 'en',
    triggers: ['marketing-coaching'],
    sopTags: ['video-ads', 'tiktok', 'reels'],
  },
  {
    id: 'neighborhood-launch',
    openElmsId: 'e69054080383bb1.15989985', title: 'Neighborhood Launch Strategy',
    description: 'Executing a successful neighborhood launch with flyers and QR codes.',
    track: 'marketing',
    tier: 'professional',
    language: 'en',
    triggers: ['host-onboarding'],
    sopTags: ['launch', 'local-marketing'],
  },
  {
    id: 'nextdoor-domination',
    openElmsId: 'e69053fa9d99af1.40435874', title: 'Nextdoor Neighborhood Domination',
    description: 'Build neighborhood goodwill and secure steady local bookings via Nextdoor.',
    track: 'marketing',
    tier: 'professional',
    language: 'en',
    triggers: ['booking-rate-low', 'neighbor-relations'],
    sopTags: ['nextdoor', 'local-marketing'],
  },
  {
    id: 'reputation-repair',
    openElmsId: 'e691efa8719d6e5.43794430', title: 'Reputation Repair: Turning Negative Reviews into Wins',
    description: 'Strategies to address legitimate complaints professionally and recover reputation.',
    track: 'marketing',
    tier: 'professional',
    language: 'en',
    triggers: ['review-below-4', 'review-below-3'],
    sopTags: ['reviews', 'reputation'],
  },
  {
    id: 'viral-tiktok-reels',
    openElmsId: 'e693fb8e9473704.89867117', title: 'Viral Pool Content: The TikTok & Reels Growth System',
    description: 'Master TikTok and Reels for pool rental businesses.',
    track: 'marketing',
    tier: 'master',
    language: 'en',
    triggers: ['marketing-coaching'],
    sopTags: ['tiktok', 'reels', 'viral'],
  },
  {
    id: 'content-the-easy-way',
    openElmsId: 'e67f51ec2881706.04458750', title: 'Creating Content the Easy Way',
    description: 'Create engaging social media content as a pool host using just your cell phone.',
    track: 'marketing',
    tier: 'professional',
    language: 'en',
    triggers: ['content-coaching'],
    sopTags: ['content', 'social-media'],
  },
  {
    id: 'canva-designer',
    openElmsId: 'e67f6b2a0d6eee9.75163206', title: 'Become a Designer with Canva',
    description: 'Comprehensive introduction to designing with Canva.',
    track: 'marketing',
    tier: 'professional',
    language: 'en',
    triggers: ['content-coaching'],
    sopTags: ['canva', 'design'],
  },
  {
    id: 'buffer-social-management',
    openElmsId: 'e67f775529c0196.47121936', title: 'Effortless Social Media Management with Buffer',
    description: 'Leverage Buffer for managing and scheduling social media posts.',
    track: 'marketing',
    tier: 'professional',
    language: 'en',
    triggers: ['content-coaching'],
    sopTags: ['buffer', 'scheduling'],
  },
  {
    id: 'eeat-writing-descriptions',
    openElmsId: 'e696638a2e09924.99864133', title: 'E-E-A-T for Hosts: Writing Descriptions that Rank',
    description: 'Optimize pool rental descriptions for search engine ranking using Google\u2019s E-E-A-T principles.',
    track: 'marketing',
    tier: 'professional',
    language: 'en',
    triggers: ['listing-quality-coaching', 'booking-rate-low'],
    sopTags: ['seo', 'copy', 'e-e-a-t'],
  },
  {
    id: 'booking-funnel-masterclass',
    openElmsId: 'e693fb87315ba73.58705612', title: 'The Booking Funnel Masterclass: From Click to Confirmed Reservation',
    description: 'Optimize the entire booking funnel from click to confirmed reservation.',
    track: 'marketing',
    tier: 'professional',
    language: 'en',
    triggers: ['booking-rate-low', 'funnel-coaching'],
    sopTags: ['funnel', 'conversion'],
  },

  // ─── Revenue & Pricing ───
  {
    id: 'upsell-amenities',
    openElmsId: 'e681bf0ab3addd5.81181840', title: 'Maximize Revenue: Upselling Pool Amenities',
    description: 'Strategies for upselling amenities on your pool rental platform.',
    track: 'revenue',
    tier: 'professional',
    language: 'en',
    triggers: ['revenue-coaching'],
    sopTags: ['upsell', 'amenities'],
  },
  {
    id: 'availability-management',
    openElmsId: 'e687f4cea111f86.45176832', title: 'PRNM Availability Management Guide',
    description: 'Effective availability management and booking optimization.',
    track: 'revenue',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding', 'low-utilization'],
    sopTags: ['calendar', 'availability'],
  },
  {
    id: 'price-variations-guide',
    openElmsId: 'e687f4c72489268.38663308', title: 'PRNM Price Variations Guide',
    description: 'Effectively use price variations to offer diverse rental packages.',
    track: 'revenue',
    tier: 'certified',
    language: 'en',
    triggers: ['host-onboarding', 'pricing-coaching'],
    sopTags: ['pricing', 'packages'],
  },
  {
    id: 'price-variations-dynamic',
    openElmsId: 'e68bf771da20bd4.66933545', title: 'Price Variations & Dynamic Pricing Guide',
    description: 'Implementing price variations and dynamic pricing strategies.',
    track: 'revenue',
    tier: 'professional',
    language: 'en',
    triggers: ['pricing-coaching'],
    sopTags: ['pricing', 'dynamic-pricing'],
  },
  {
    id: 'pricing-strategy-dynamic-revenue',
    openElmsId: 'e6896b335b8fcf6.47746949', title: 'Pricing Strategy & Dynamic Revenue Management Guide',
    description: 'Master pricing strategy and dynamic revenue management.',
    track: 'revenue',
    tier: 'master',
    language: 'en',
    triggers: ['pricing-coaching', 'revenue-coaching'],
    sopTags: ['pricing', 'revenue-management'],
  },
  {
    id: 'equipment-rental-upsell',
    openElmsId: 'e68bf6a77b5ef54.94996142', title: 'Pool Equipment Rental & Upsell Strategies',
    description: 'Transform your pool rental into a premium, revenue-generating machine.',
    track: 'revenue',
    tier: 'professional',
    language: 'en',
    triggers: ['revenue-coaching'],
    sopTags: ['upsell', 'equipment'],
  },
  {
    id: 'cost-per-swim',
    openElmsId: 'e6905409432fdd1.82662572', title: 'Cost-Per-Swim Modeling for Pool Hosts',
    description: 'Develop a clear, defensible cost model for your pool rentals.',
    track: 'revenue',
    tier: 'professional',
    language: 'en',
    triggers: ['pricing-coaching'],
    sopTags: ['cost-modeling', 'pricing'],
  },
  {
    id: 'calendar-sync-warfare',
    openElmsId: 'e69663761a5ea08.62059455', title: 'Calendar Sync Warfare: Preventing Double Bookings',
    description: 'Prevent double bookings for hosts managing properties across multiple platforms.',
    track: 'revenue',
    tier: 'certified',
    language: 'en',
    triggers: ['double-booking', 'calendar-conflict'],
    sopTags: ['calendar', 'sync', 'operations'],
  },
  {
    id: '10k-month-blueprint',
    openElmsId: 'e693fba49e24109.95759849', title: 'The $10K Month Blueprint: Scaling from Side Hustle to Full-Time Income',
    description: 'Strategic blueprint for transforming a side hustle into a full-time $10K/mo income.',
    track: 'revenue',
    tier: 'master',
    language: 'en',
    triggers: ['scale-coaching', 'revenue-coaching'],
    sopTags: ['scaling', 'revenue'],
  },
  {
    id: 'premium-positioning',
    openElmsId: 'e693fb86de7c6f4.71343078', title: 'Premium Positioning: Charge 3x Your Competition',
    description: 'Strategic art of premium positioning to command significantly higher rates.',
    track: 'revenue',
    tier: 'master',
    language: 'en',
    triggers: ['pricing-coaching'],
    sopTags: ['premium-positioning', 'pricing'],
  },
  {
    id: 'convenience-upsell-playbook',
    openElmsId: 'e69aff09638c140.88742327', title: 'The "Convenience" Upsell Playbook',
    description: 'Boost earnings with convenient, high-margin items guests often forget.',
    track: 'revenue',
    tier: 'professional',
    language: 'en',
    triggers: ['revenue-coaching'],
    sopTags: ['upsell', 'convenience'],
  },

  // ─── Events & Niche Hosting ───
  {
    id: 'pet-friendly-rentals',
    openElmsId: 'e68ef4f6c3bc7b3.63687767', title: 'Pet-Friendly Pool Rentals',
    description: 'Essential guidance for hosts offering pet-friendly pool rentals.',
    track: 'events',
    tier: 'professional',
    language: 'en',
    triggers: ['pet-booking-inquiry'],
    sopTags: ['pet-friendly', 'specialty'],
  },
  {
    id: 'special-needs-accessibility',
    openElmsId: 'e6896b2a8e532a3.99899168', title: 'Hosting for Special Needs & Inclusive Aquatic Accessibility',
    description: 'Provide safe, respectful, and dignified aquatic access for guests with special needs.',
    track: 'events',
    tier: 'professional',
    language: 'en',
    triggers: ['accessibility-inquiry'],
    sopTags: ['accessibility', 'inclusivity'],
  },
  {
    id: 'clothing-optional',
    openElmsId: 'e6896b78c2da3f1.82250509', title: 'Guide: Allowing Nude (Clothing-Optional) Swimming',
    description: 'Safely and responsibly offering clothing-optional swimming.',
    track: 'events',
    tier: 'master',
    language: 'en',
    triggers: ['niche-market-coaching'],
    sopTags: ['niche', 'clothing-optional'],
  },
  {
    id: 'tiered-experience-packages',
    openElmsId: 'e6896b635baf0a6.86348581', title: 'Guide: Designing Tiered Experience Packages',
    description: 'Designing tiered experience packages for wellness swim venues.',
    track: 'events',
    tier: 'professional',
    language: 'en',
    triggers: ['package-design-coaching'],
    sopTags: ['packages', 'wellness'],
  },
  {
    id: 'corporate-retreat-hosting',
    openElmsId: 'e68bf679daaed49.12552267', title: 'Corporate Retreat & Team Building Hosting Guide',
    description: 'Comprehensive insights for hosts offering pool rentals for corporate events.',
    track: 'events',
    tier: 'professional',
    language: 'en',
    triggers: ['corporate-inquiry'],
    sopTags: ['corporate', 'events'],
  },
  {
    id: 'kids-birthday-parties',
    openElmsId: 'e691efa71e74bc2.26230870',
    title: 'Hosting High-Revenue Kids\u2019 Birthday Parties',
    description: 'Intricate logistics of organizing profitable kids\u2019 birthday parties.',
    track: 'events',
    tier: 'professional',
    language: 'en',
    triggers: ['birthday-party-inquiry'],
    sopTags: ['birthday-parties', 'events'],
  },
  {
    id: 'swimming-lesson-integration',
    openElmsId: 'e68bf6e274d8dc5.30523494', title: 'Swimming Lesson Integration for Hosts',
    description: 'Integrate swimming lessons into your offerings.',
    track: 'events',
    tier: 'professional',
    language: 'en',
    triggers: ['lesson-partnership-inquiry'],
    sopTags: ['swimming-lessons', 'partnerships'],
  },
  {
    id: 'therapeutic-pool-programs',
    openElmsId: 'e68bf6fa5144b39.63084320', title: 'How to Start Comprehensive Therapeutic Pool Programs',
    description: 'Establish comprehensive therapeutic pool programs.',
    track: 'events',
    tier: 'master',
    language: 'en',
    triggers: ['therapy-partnership-inquiry'],
    sopTags: ['therapy', 'partnerships', 'wellness'],
  },
  {
    id: 'after-dark-night-swims',
    openElmsId: 'e691efadc156473.61171162', title: 'After-Dark Hosting: Lighting Aesthetics & Night Swims',
    description: 'Explore the art of after-dark hosting for night swims.',
    track: 'events',
    tier: 'professional',
    language: 'en',
    triggers: ['night-booking-inquiry'],
    sopTags: ['night-swim', 'ambiance'],
  },
  {
    id: 'gender-reveals',
    openElmsId: 'e69663be4f30fa9.59573525', title: 'Hosting Gender Reveals: Managing Dye, Smoke & Confetti',
    description: 'Elaborate gender reveal parties, focusing on environmental and property damage prevention.',
    track: 'events',
    tier: 'professional',
    language: 'en',
    triggers: ['gender-reveal-inquiry', 'property-damage-concern'],
    sopTags: ['gender-reveal', 'event-safety'],
  },
  {
    id: 'baptisms-church-partnerships',
    openElmsId: 'e696636d54ada31.90050308', title: 'Baptisms & Church Partnerships',
    description: 'Growing need for church partnerships for baptismal facilities.',
    track: 'events',
    tier: 'professional',
    language: 'en',
    triggers: ['church-partnership-inquiry'],
    sopTags: ['baptism', 'partnerships', 'church'],
  },
  {
    id: 'wedding-venue-positioning',
    openElmsId: 'e693fbc3d8a0d03.13432735', title: 'Wedding & Event Venue Positioning for Pools',
    description: 'Position poolside venues for weddings and high-end events.',
    track: 'events',
    tier: 'master',
    language: 'en',
    triggers: ['wedding-inquiry', 'event-coaching'],
    sopTags: ['weddings', 'events', 'positioning'],
  },
  {
    id: 'catering-food-truck',
    openElmsId: 'e69aff0159f37e2.31733588', title: 'Catering & Food Truck Alliances',
    description: 'Logistics of accommodating outside catering and food trucks for larger events.',
    track: 'events',
    tier: 'professional',
    language: 'en',
    triggers: ['large-event-inquiry'],
    sopTags: ['catering', 'food-truck', 'events'],
  },
  {
    id: 'backyard-carnivals',
    openElmsId: 'e69aff068b9aa80.15842023', title: 'Backyard Carnivals & Themed Mega-Parties',
    description: 'Transform standard pool offerings into full-scale festival experiences.',
    track: 'events',
    tier: 'master',
    language: 'en',
    triggers: ['mega-party-inquiry'],
    sopTags: ['mega-parties', 'themed-events'],
  },
  {
    id: 'dry-patio-events',
    openElmsId: 'e69aff151273b47.32106471', title: 'Hosting "Dry" Patio Events',
    description: 'Unlock new revenue by using backyard space for non-swim events.',
    track: 'events',
    tier: 'professional',
    language: 'en',
    triggers: ['dry-event-inquiry'],
    sopTags: ['patio', 'dry-events'],
  },
  {
    id: 'dive-shop-partnership',
    openElmsId: 'e6966388844abb2.90807995', title: 'Partnering with Dive Shops: Hosting Scuba Certification',
    description: 'Mutually beneficial partnership between deep-water facilities and dive shops.',
    track: 'events',
    tier: 'master',
    language: 'en',
    triggers: ['scuba-partnership-inquiry'],
    sopTags: ['scuba', 'partnerships'],
  },
  {
    id: 'scuba-snorkel-mermaid',
    openElmsId: 'e69aff05a450741.58181154', title: 'Scuba, Snorkel & Mermaid Certification Hosting',
    description: 'Transform deep pools into prime locations for aquatic certifications.',
    track: 'events',
    tier: 'master',
    language: 'en',
    triggers: ['certification-inquiry'],
    sopTags: ['scuba', 'mermaid', 'certifications'],
  },
  {
    id: 'fitness-bootcamps',
    openElmsId: 'e69aff05fdb5965.92968935', title: 'Fitness Bootcamps & Water Aerobics',
    description: 'Expand offerings by partnering with local fitness instructors.',
    track: 'events',
    tier: 'professional',
    language: 'en',
    triggers: ['fitness-partnership-inquiry'],
    sopTags: ['fitness', 'water-aerobics', 'partnerships'],
  },

  // ─── Brand & Growth ───
  {
    id: 'elevate-branding',
    openElmsId: 'e681be94281c6e1.73160890', title: 'Elevate Your Pool with Branding',
    description: 'Importance of branding and how to create and implement a brand strategy.',
    track: 'growth',
    tier: 'master',
    language: 'en',
    triggers: ['brand-coaching'],
    sopTags: ['branding'],
  },
  {
    id: 'become-top-host',
    openElmsId: 'e67f520c8302b05.26455341', title: 'Become a Top Host: Transforming Pool Rentals',
    description: 'Strategic guide to transforming traditional pool rentals into a premium marketplace offering.',
    track: 'growth',
    tier: 'master',
    language: 'en',
    triggers: ['growth-coaching'],
    sopTags: ['premium', 'top-host'],
  },
  {
    id: 'prnm-management-business',
    openElmsId: 'e68bf6b69065068.88285655', title: 'Start a Business with PRNM Pool Management',
    description: 'Manage private pool rentals through the PRNM Pool Management platform.',
    track: 'growth',
    tier: 'master',
    language: 'en',
    triggers: ['growth-coaching'],
    sopTags: ['management-business'],
  },
  {
    id: 'second-rental-property',
    openElmsId: 'e691efa2ab6e0d2.75095526', title: 'Scaling Up: Buying Your Second Rental Property',
    description: 'Guide from single rental property to multi-property investor.',
    track: 'growth',
    tier: 'master',
    language: 'en',
    triggers: ['scale-coaching'],
    sopTags: ['scaling', 'real-estate'],
  },
  {
    id: 'green-operations',
    openElmsId: 'e68bf6cac8c1a63.07341603', title: 'PRNM Green Operations Revolution',
    description: 'Transformative power of sustainable pool operations.',
    track: 'growth',
    tier: 'professional',
    language: 'en',
    triggers: ['sustainability-coaching'],
    sopTags: ['sustainability', 'eco'],
  },
  {
    id: 'cancellation-rain-checks',
    openElmsId: 'e691ef9cf4737d3.83842812', title: 'Weathering the Storm: Cancellation Policies & Rain Checks',
    description: 'Craft fair but firm cancellation policies during bad weather.',
    track: 'growth',
    tier: 'certified',
    language: 'en',
    triggers: ['cancellation-dispute', 'weather-cancellation'],
    sopTags: ['cancellations', 'weather'],
  },
  {
    id: 'multi-property-empire',
    openElmsId: 'e693fbeb82c3902.79335908', title: 'Building a Pool Rental Empire: Multi-Property Management',
    description: 'Establishing and scaling a successful multi-property pool rental business.',
    track: 'growth',
    tier: 'master',
    language: 'en',
    triggers: ['scale-coaching'],
    sopTags: ['multi-property', 'scaling'],
  },

  // ─── Cross-track / AI & Tech ───
  {
    id: 'ai-for-pool-hosts',
    openElmsId: 'e67f52ad46cdec4.19792646', title: 'AI for Pool Hosts',
    description: 'How artificial intelligence can enhance pool business operations.',
    track: 'growth',
    tier: 'professional',
    language: 'en',
    triggers: ['efficiency-coaching'],
    sopTags: ['ai', 'automation'],
  },
  {
    id: 'ai-gpt-beginners',
    openElmsId: 'e67f6b0ccc22d23.63983268', title: 'AI & GPT for Beginners',
    description: 'Introduces beginners to using AI and GPT for optimizing listings.',
    track: 'growth',
    tier: 'professional',
    language: 'en',
    triggers: ['content-coaching'],
    sopTags: ['ai', 'gpt'],
  },
  {
    id: 'data-privacy-cybersecurity',
    openElmsId: 'e691efb452132e2.34409160', title: 'Data Privacy & Cybersecurity for Smart Pool Hosts',
    description: 'Essential knowledge on data privacy and cybersecurity.',
    track: 'legal',
    tier: 'professional',
    language: 'en',
    triggers: ['security-coaching'],
    sopTags: ['privacy', 'cybersecurity'],
  },
  {
    id: 'security-camera-practices',
    openElmsId: 'e68ef4f4dc6d9b0.86474997', title: 'Security Camera Best Practices for Pool Rentals',
    description: 'Essential best practices regarding security cameras at pool rentals.',
    track: 'legal',
    tier: 'certified',
    language: 'en',
    triggers: ['camera-compliance', 'host-onboarding'],
    sopTags: ['cameras', 'security'],
  },
  {
    id: 'time-management',
    openElmsId: 'e68ef4fc072d678.76145180', title: 'Time Management for Pool Hosts',
    description: 'Essential time management strategies tailored for pool hosts.',
    track: 'growth',
    tier: 'professional',
    language: 'en',
    triggers: ['efficiency-coaching'],
    sopTags: ['time-management', 'productivity'],
  },
  {
    id: 'music-audio-systems',
    openElmsId: 'e68ef4d1aa9d889.50461258', title: 'Music & Audio Systems for Pool Areas',
    description: 'Designing, installing, and managing audio systems for pool areas.',
    track: 'operations',
    tier: 'professional',
    language: 'en',
    triggers: ['ambiance-coaching', 'neighbor-complaint-noise'],
    sopTags: ['audio', 'ambiance'],
  },

  // ─── Property Damage + Insurance ───
  {
    id: 'property-damage-docs',
    openElmsId: 'e693fbb08468607.51908194', title: 'Dealing with Property Damage: Documentation, Claims & Recovery',
    description: 'Essential steps for documenting and recovering from property damage.',
    track: 'legal',
    tier: 'certified',
    language: 'en',
    triggers: ['property-damaged', 'damage-reported'],
    sopTags: ['damage', 'claims', 'documentation'],
  },
  {
    id: 'damage-control-insurance',
    openElmsId: 'e69aff0cc2bd921.58388958', title: 'Damage Control: Navigating Insurance Claims & Repairs',
    description: 'Essential action plan for managing property damage and insurance claims.',
    track: 'legal',
    tier: 'certified',
    language: 'en',
    triggers: ['property-damaged', 'insurance-claim'],
    sopTags: ['insurance', 'claims', 'damage'],
  },

  // ─── Neighbor & community ───
  {
    id: 'neighbor-community-relations',
    openElmsId: 'e6896b3075e9ce2.77773270', title: 'Neighbor & Community Relations / Noise & Nuisance Mitigation',
    description: 'Foster positive neighbor and community relations while mitigating noise nuisance.',
    track: 'hospitality',
    tier: 'certified',
    language: 'en',
    triggers: ['neighbor-complaint', 'neighbor-complaint-noise'],
    sopTags: ['neighbor-relations', 'noise'],
  },
  {
    id: 'neighbor-complaints-realtime',
    openElmsId: 'e68ef4fc4bc0ac6.70181023', title: 'Dealing with Neighbor Complaints in Real-Time',
    description: 'Effectively manage neighbor complaints with de-escalation techniques.',
    track: 'hospitality',
    tier: 'certified',
    language: 'en',
    triggers: ['neighbor-complaint', 'police-called'],
    sopTags: ['neighbor-relations', 'de-escalation'],
  },
  {
    id: 'parking-traffic-flow',
    openElmsId: 'e69aff099e86942.68588525', title: 'Managing Parking & Neighborhood Traffic Flow',
    description: 'Managing parking and traffic flow in residential neighborhoods.',
    track: 'hospitality',
    tier: 'certified',
    language: 'en',
    triggers: ['parking-complaint', 'neighbor-complaint'],
    sopTags: ['parking', 'traffic', 'neighbor-relations'],
  },

  // ─── Amenities & enhancement ───
  {
    id: 'shade-cabana-experience',
    openElmsId: 'e69aff1255a4157.43514694', title: 'Designing the Ultimate Shade & Cabana Experience',
    description: 'Transform pool areas into luxurious shaded retreats.',
    track: 'operations',
    tier: 'professional',
    language: 'en',
    triggers: ['amenity-coaching'],
    sopTags: ['shade', 'cabana', 'amenities'],
  },
  {
    id: 'luxury-landscaping-budget',
    openElmsId: 'e69aff10895ee54.55253915', title: 'Luxury Landscaping & Staging on a Budget',
    description: 'Transform backyards into luxurious retreats without breaking the bank.',
    track: 'operations',
    tier: 'professional',
    language: 'en',
    triggers: ['listing-quality-coaching'],
    sopTags: ['landscaping', 'staging'],
  },

  // ─── Environmental ───
  {
    id: 'drought-water-restrictions',
    openElmsId: 'e69aff14d20b738.71852302', title: 'Navigating Local Drought & Water Restrictions',
    description: 'Managing swimming pools during municipal water bans.',
    track: 'operations',
    tier: 'professional',
    language: 'en',
    triggers: ['drought-alert', 'water-restriction'],
    sopTags: ['drought', 'water-conservation', 'compliance'],
  },

  // ─── Bilingual / Spanish ───
  {
    id: 'bilingual-operations',
    openElmsId: 'e69aff09b2f5894.34462487', title: 'Bilingual Hosting Operations',
    description: 'Welcome Spanish-speaking guests with confidence and cultural sensitivity.',
    track: 'hospitality',
    tier: 'professional',
    language: 'en',
    triggers: ['bilingual-coaching'],
    sopTags: ['bilingual', 'spanish'],
  },
  {
    id: 'aprende-rentar-piscina',
    openElmsId: null,
    title: 'Aprende a Rentar tu Piscina',
    description: 'Curso completo en espa\u00f1ol para anfitriones de alquiler de piscinas — seguridad, hospitalidad y operaciones.',
    track: 'hospitality',
    tier: 'certified',
    language: 'es',
    triggers: ['host-onboarding-spanish'],
    sopTags: ['spanish', 'host-onboarding'],
  },
  {
    id: 'digital-waivers-roi',
    openElmsId: 'e69aff06baadef4.20925884', title: 'Mastering Digital Waivers, ROI Calculators & Signage',
    description: 'Digital tools and practical strategies to enhance your pool rental business.',
    track: 'operations',
    tier: 'professional',
    language: 'en',
    triggers: ['host-onboarding'],
    sopTags: ['waivers', 'roi', 'signage'],
  },
];

// ─── Helpers ────────────────────────────────────────────
export const getCoursesByTrack = trackId =>
  COURSES.filter(c => c.track === trackId);

export const getCoursesByTier = tierId =>
  COURSES.filter(c => {
    if (tierId === 'certified') return c.tier === 'certified';
    if (tierId === 'professional') return ['certified', 'professional'].includes(c.tier);
    if (tierId === 'master') return true;
    return false;
  });

/**
 * Reactive coaching: given a problem event tag (e.g. "review-below-4-cleanliness"),
 * return the best-matching courses so the platform can say "here's how we do this."
 */
export const getCoursesByTrigger = triggerTag =>
  COURSES.filter(c => c.triggers?.includes(triggerTag));

/**
 * Compute the host's current certification tier given a Set of completed course ids.
 */
export const computeCertificationTier = (completedIds = new Set()) => {
  const certifiedCourses = getCoursesByTier('certified').map(c => c.id);
  const professionalCourses = getCoursesByTier('professional').map(c => c.id);
  const masterCourses = COURSES.map(c => c.id);

  const certifiedDone = certifiedCourses.every(id => completedIds.has(id));
  const professionalDone = professionalCourses.every(id => completedIds.has(id));
  const masterDone = masterCourses.every(id => completedIds.has(id));

  if (masterDone) return 'master';
  if (professionalDone) return 'professional';
  if (certifiedDone) return 'certified';
  return null;
};

/**
 * Compute progress numbers for the certification ladder UI.
 * Returns { certified: {done, total}, professional: {done, total}, master: {done, total} }
 */
export const computeLadderProgress = (completedIds = new Set()) => {
  const compute = tierCourses => ({
    done: tierCourses.filter(id => completedIds.has(id)).length,
    total: tierCourses.length,
  });
  return {
    certified: compute(getCoursesByTier('certified').map(c => c.id)),
    professional: compute(getCoursesByTier('professional').map(c => c.id)),
    master: compute(COURSES.map(c => c.id)),
  };
};

export const getCourseById = id => COURSES.find(c => c.id === id);

export const getOpenElmsEmbedUrl = course => {
  if (!course?.openElmsId) return null;
  return `https://openelms.ai/embed/${course.openElmsId}/`;
};
